### ISSUE TITLE
Not working with gatsby image plugin (StaticImage)

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#347]
## Issue Type

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

## Description

@lezan reported an issue with using the `gatsby-image-plugin` here: https://github.com/rpearce/react-medium-image-zoom/discussions/274#discussioncomment-3384320. They graciously provided a examples:

* Test repo: https://github.com/lezan/zoom-test-gatsby
* Online demo: https://codesandbox.io/s/sharp-pike-fzr2ye?file=/src/pages/index.js

**Comment by rpearce** [comment]
After a good deal of investigation tonight, it looks like the actual `<img>` element we want to hook into isn't present on the page _at all_ at render time. If there's no image on the page, the `querySelector` code can't find it, and it's difficult to know when the image is actually injected onto the page (would I need an expensive `MutationObserver`?).

Luckily, the Gatsby component in question has an `onLoad` callback, so here's a workaround:

```jsx
import React, { useCallback, useState } from "react"
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'

// ... then in your component

const [isImgLoaded, setIsImgLoaded] = useState(false)
const handleImgLoad = useCallback(() => setIsImgLoaded(true), [])
const ZoomComp = isImgLoaded ? Zoom : 'div'

// ... then

<ZoomComp>
  <StaticImage
    src="../images/earth-large.jpg"
    alt="test image for test"
    onLoad={handleImgLoad}
    placeholder="blurred"
    layout="constrained"
    width={1920}
    height={1080}
    className="image-zoom"
  />
</ZoomComp>
```

**Comment by rpearce** [comment]
While this works for `gatsby develop`, it's looking like this doesn't work after `gatsby build` because the `onLoad` isn't getting fired :(

I'll keep trying in the next couple of nights.

**Comment by rpearce** [comment]
Update: I've almost got it perfect, but the zoom causes a little flash on the first load. Almost there!

**Comment by rpearce** [comment]
Update: I've figured it out. I'll do some more testing and put up a PR tonight, I think.

**Comment by rpearce** [comment]
My solution at present is with using some exponential backoff recursion (sounds way fancier than it is), but I'm going to try to see if I can do a simple `MutationObserver`, instead. It would only be used in the event that an image wasn't found, and then it would stop observing once one was found.

**Comment by rpearce** [comment]
This should be fixed in `react-medium-image-zoom@5.0.2-beta.0`, and I plan on releasing `5.0.2` in the next couple of days.

**Comment by lezan** [comment]
Hello @rpearce, it seems issue is still here but different in someway. Not sure if I did something wrong, but you can check the online example and also the repo (they are both updated).

**Comment by rpearce** [comment]
@lezan I'll check it out very soon! I've got some time.

**Comment by rpearce** [comment]
@lezan Did you run `yarn install` after you merged the code? I just merged your upstream code into my fork, and it's working on macOS in Chrome, Firefox, and Safari.

**Comment by rpearce** [comment]
@lezan Your online example still has an issue with it. You need to delete this line:

```
```

**Comment by lezan** [comment]
Hello @rpearce you are right about the online example, I thought it was synced with the Github repo, but it is not.  After a `yarn clean` also my test repo is working (I already removed `css`, `role` and run `yarn install`. Going to test it on my main project and testing in development to give you more feedback.

**Comment by rpearce** [comment]
Sounds good. If it's satisfactory, we can 🚢 :shipit:!

**Comment by rpearce** [comment]
@lezan This seems like the original issue is fixed. I'm adding you as an "All Contributor" to the README for your contribution here (bug report, ideas, helping work through it). You can upgrade to `5.0.2` at your convenience to get this fix in your app(s).

Also be on the lookout for `5.1.0` soon; it'll support https://github.com/rpearce/react-medium-image-zoom/issues/332
